#################################################################################
# ALGORITHM
#################################################################################
# Discount factor in reinforcement learning
discount: 0.9

# Learning rate for actor (inner loop)
actor_lr_inner: 0.01

# Learning rate for actor (outer loop)
actor_lr_outer: 0.00001

# Learning rate for value (outer loop)
value_lr: 0.000015

# Entropy weight in the meta-optimization
entropy_weight: 0

# Markov chain terminates when chain horizon is reached
chain_horizon: 7

#################################################################################
# ENV
#################################################################################
# OpenAI gym environment name
env_name: "RPS-v0"  

# Episode terminates when horizon is reached
ep_horizon: 50

# If True, scale reward for train stabilization
reward_scale: False
